# Generated by Django 4.2.3 on 2023-09-18 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balaji_sports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_sale',
            field=models.BooleanField(default=False),
        ),
    ]
