# Generated by Django 4.2.3 on 2023-09-18 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balaji_sports', '0003_product_product_desc_product_product_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_img',
            field=models.ImageField(null=True, upload_to='media/pics'),
        ),
    ]
