# Generated by Django 4.2.3 on 2023-09-18 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balaji_sports', '0005_alter_product_product_desc_alter_product_product_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_img',
            field=models.ImageField(default='', upload_to='pics/'),
        ),
    ]
