# Generated by Django 4.2.3 on 2023-09-23 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('balaji_sports', '0009_alter_product_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_id',
        ),
    ]
