# Generated by Django 4.2.3 on 2023-09-25 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balaji_sports', '0018_product_best_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='master_best_seller',
            field=models.BooleanField(default=False),
        ),
    ]
