# Generated by Django 4.2.3 on 2023-10-01 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balaji_sports', '0019_product_master_best_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='best_seller',
        ),
        migrations.AddField(
            model_name='product',
            name='catagory',
            field=models.CharField(choices=[('Simple', 'Simple'), ('Master', 'Master')], default='Simple', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='simple_best_seller',
            field=models.BooleanField(default=False),
        ),
    ]
