# Generated by Django 4.2.3 on 2023-11-02 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balaji_sports', '0020_remove_product_best_seller_product_catagory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Master_kit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='Simple_kit',
            field=models.BooleanField(default=False),
        ),
    ]
