# Generated by Django 4.2.3 on 2023-11-07 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balaji_sports', '0021_product_master_kit_product_simple_kit'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_price',
            field=models.IntegerField(default=''),
        ),
    ]
