# Generated by Django 4.2.3 on 2023-11-07 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balaji_sports', '0022_product_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_sale_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
