# Generated by Django 4.2.3 on 2024-01-21 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('balaji_sports', '0024_order_cart'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cart',
            new_name='Order_Item',
        ),
    ]
