# Generated by Django 4.2.3 on 2024-01-21 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('balaji_sports', '0025_rename_cart_order_item'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order_Item',
            new_name='OrderItem',
        ),
    ]
